[tools]
selene = {source = "Kampfkarren/selene", version = "x"}
wally = {source = "UpliftGames/wally", version = "0.3.1"}
luau-lsp = { source = "JohnnyMorganz/luau-lsp", version = "*" }
remodel = { source = "rojo-rbx/remodel", version = "0.11.0" }
luau-analyze = { source = "JohnnyMorganz/luau-analyze-rojo", version = "*" }